### ISSUE TITLE
 A software watchdog timer with uasyncio support

### ISSUE THREAD

**Issue by beyonlo** [peterhinch/micropython-samples#30]
Hello @peterhinch!

I see in your [software watchdog timer example](https://github.com/peterhinch/micropython-samples/tree/master/soft_wdt) and I would like to use it with my `uasyncio` applications. Do you have a `uasyncio` version of that? If I just change the `sleeps` by a`wait uasyncio.sleep()` and add `async` before of the functions `(def)` is correct, or need others deep changes to works correctly with `uasyncio`?

I'm using `ESP32-S3` with `MicroPython 1.19.1`. My intention is to save all data that I have in the RAM into the flash before system reset by watchdog - the flash is very slow to save everytime. As the [hardware watchdog](https://docs.micropython.org/en/latest/library/machine.WDT.html) is not possible to dot that (save data into the flash before the watchdog reset), I would like to use your software watchdog.

Thank you in advance!

**Comment by peterhinch** [comment]
The point of a WDT is that it should take control if the main program fails.

There is a [delay_ms](https://github.com/peterhinch/micropython-async/blob/master/v3/docs/TUTORIAL.md#38-delay_ms-class) class in my `uasyncio` repo which can initiate an action if it is not repeatedly triggered: you could use this as it stands. However this is not a WDT. If `uasyncio` fails - prehaps because a task blocks forever - the `delay_ms` instance will not work.

The software WDT solves this by being triggered by a timer. So my advice would be to use it as it stands, simply adding your file save command before the [reset instruction](https://github.com/peterhinch/micropython-samples/blob/b2a0c6f17d62950a38253936916f4936b363e708/soft_wdt/soft_wdt.py#L35).

Note that a software WDT is not as good as a hardware one. If MicroPython crashes, the software WDT will not work. But it will work if `uasyncio` locks up, because the software timer is independent of `uasyncio`.
